name: Upload SCPI docs
on:
  workflow_dispatch:
    inputs:
      version:
        description: release/snapshot version
        required: true
        type: string

jobs:
  run:
    runs-on: ubuntu-latest
    container:
      image: schnitzeltony/fedora-qt5:32
    steps:
      - name: Echo github environment
        run: |
          echo "Home: $HOME"
          echo "Workspace: $GITHUB_WORKSPACE"

      - name: Download zera-classes's scpi-docs artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          repo: ZeraGmbH/zera-classes
          name: scpi-docs-artifact
          workflow: generateScpiDocs.yml

      - name: Untar zera-classes's scpi-docs artifact
        run: |
            tar -xf scpi_docs.tar.xz -C /
            rm scpi_docs.tar.xz
            ls -la $HOME/

      - name: Checkout git
        uses: actions/checkout@v4

      - name: Commit scpi-docs
        run: |
          git config --global user.name 'gitbot'
          git config --global user.email 'gitbot@noreply.de'
          mkdir -p scpi-documentation && cd scpi-documentation
          cp -r $HOME/html-docs/* .
          mkdir -p archive
          tar -cJf archive/${{ github.event.inputs.version}}.tar.xz *.html
          cd ..
          pip3 install mdutils
          python3 updateReadMe.py --ZenuxVersion ${{ github.event.inputs.version}} --SessionNamesJson $HOME/SessionNamesMapping.json
          git add .
          git commit -sm "Update scpi-docs for Zenux version ${{ github.event.inputs.version}}"
          git push
